### ISSUE TITLE
Add m3u support 

### ISSUE THREAD

**Issue by modenwenda** [MobinurRahaman/ellipto-iptv#5]
Add m3u support  so i can show visitors pre loaded channel

**Comment by MobinurRahaman** [comment]
The issue has been resolved with the latest commit. The bug was related to HLS playback, and downgrading the HLS package to version 1.4.14 fixed it. You can verify the fix by testing with the updated code. 

Link to the original issue: [Issue #379](https://github.com/vime-js/vime/issues/379#issue-2076475199)

Note: The reported errors started after the Chrome, Edge, Safari update on 10.01.24.
