### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Fannangir** [MobinurRahaman/ellipto-iptv#6]
Is there a possibility to create a docker image?

Thanks.

**Comment by Itz-Agasta** [comment]
Hi, @MobinurRahaman I've created a PR to add Docker support for local development and testing as requested by @Fannangir! Could you take a look and let me know if there are any adjustments you'd like?

Also, would you like me to:

- Update the README with Docker usage instructions?
- Deploy the image to Docker Hub?

Thanks!

**Comment by Fannangir** [comment]
Thank you very much for the quick action.
Sure, please do :).
A docker compose example would be great as well.
Thank you very much!

**Comment by Itz-Agasta** [comment]
@Fannangir, This project doesn’t currently require a `docker-compose.yml` because it follows a Single Service Architecture. It’s a standalone React frontend that relies solely on client-side storage (Dexie.js) without any external databases or additional services to manage. Therefore, the existing Dockerfile suffices for containerization.

That said, if you’d like a docker-compose.yml added for future development scenarios—such as integrating backend services or databases—I’d be happy to help set it up. Just let me know!

**Comment by Fannangir** [comment]
@Itz-Agasta Thanks for creating the docker support.
Could you please add to docker hub so I can just pull it?
Thanks.

**Comment by Itz-Agasta** [comment]
> @Itz-Agasta Thanks for creating the docker support. Could you please add to docker hub so I can just pull it? Thanks.

Hi! @Fannangir Sure, I’ll create it and upload it to Docker Hub. You can send me a request on Discord—my username is agasta69 or you can follow this link: https://discordapp.com/users/720146996475985980. I’ll let you know as soon as it’s done!

**Comment by Fannangir** [comment]
@Itz-Agasta Thank you very much.
Sent a friend request.
